plugins {
    id 'pickdeal-springboot'
    id 'pickdeal-springcloud'
}

group = 'com.leui'
version = '0.0.1-SNAPSHOT'
description = 'eureka-server'


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}