gateway:
  base-url: http://localhost:8888
kakao:
  cid: TC0ONETIME  # 테스트용 가맹점 코드 (실제 운영시 변경)
spring:
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    consumer:
      group-id: order-service
